### ISSUE TITLE
Unable to insert between media block and list

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#100]
Maybe another case for `<p>` padding?
![ed-insert](https://cloud.githubusercontent.com/assets/885369/13419998/5df4f384-df37-11e5-8894-3cea157f143c.gif)

**Comment by nickvelloff** [comment]
Also discovered that I can't insert _after_ the list as well.

**Comment by forresto** [comment]
Is the issue the keyboard not showing? If not there is the "Lift out of enclosing block" button.

**Comment by nickvelloff** [comment]
No this is actually just the ability to insert between the image block and the list. 
Also after the list there does not seem to be a 'p' so an insertion can be made.

**Comment by nickvelloff** [comment]
FYI when using the simulator to test the keyboard often will not open and we just use the "real" keyboard. Mouse clicks are interpreted as touches.

**Comment by forresto** [comment]
Cursor at end of last list item: enter, enter
Cursor at start of list: enter, focus empty "1." item, press ![Lift out of enclosing block](https://cloud.githubusercontent.com/assets/395307/13435967/f3ecf9c2-dfaa-11e5-9da9-35931c6dc803.png) button

**Comment by nickvelloff** [comment]
:+1: ... I guess my natural tendency was to just try to touch above or below. :bow:
