### ISSUE TITLE
iOS 8.3 - Ed crash when calling getContent()

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#105]
iPhone 5 (iOS 8.3) simulator I get an Ed crash when iOS calls `window.ed.getContent();`
This does not happen on iOS 9.

The specific line it crashes on is this

``` Javascript
// Should use debounced version
function onDOMChanged () {
  // Mount or move widget overlays
  const els = this.ed.pm.content.querySelectorAll('div[grid-type]')
  let inDoc = []
  for (let i = 0, len = els.length; i < len; i++) { // <-- this one
```

<img width="781" alt="screenshot 2016-03-01 11 07 57" src="https://cloud.githubusercontent.com/assets/885369/13438451/ec509f6e-df9d-11e5-9496-58e405abccef.png">
![screenshot 2016-03-01 11 05 29](https://cloud.githubusercontent.com/assets/885369/13438456/f36f3b20-df9d-11e5-8956-14340d596402.png)

**Comment by nickvelloff** [comment]
Little more info: 
it is crashing when trying to evaluate `d.children.length`
This is `d`:
<img width="287" alt="screenshot 2016-03-01 11 52 23" src="https://cloud.githubusercontent.com/assets/885369/13439863/3a5734c4-dfa4-11e5-9c16-8cafe4141bae.png">

**Comment by forresto** [comment]
`els.length` != `d.children.length` ... having trouble tracking the browser inconsistency down. Still have the issue with 0.6.0? Will try browserstack.

**Comment by forresto** [comment]
Looks like crash is actually here https://github.com/the-grid/ed/blob/fb31318d1c00ce472f869927dd2e05502d5274b5/src/convert/doc-to-grid.js#L7

(Browserstack has gotten better since last time I used it :+1:)
