### ISSUE TITLE
iOS 9 TypeError: undefined is not an object (evaluating 'this.initialBlock.type') triggered by setContent()

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#106]
`initialBlock` is `undefined` here and is erring out.

<img width="268" alt="screenshot 2016-03-01 16 12 35" src="https://cloud.githubusercontent.com/assets/885369/13446453/7c3ba1bc-dfc8-11e5-8aea-9047cd3a0a44.png">

![screenshot 2016-03-01 16 10 43](https://cloud.githubusercontent.com/assets/885369/13446449/748a9662-dfc8-11e5-8544-74d5fa04dd2f.png)

<img width="474" alt="screenshot 2016-03-01 16 15 43" src="https://cloud.githubusercontent.com/assets/885369/13446489/e0b43726-dfc8-11e5-9e43-b28de3918bce.png">

**Comment by nickvelloff** [comment]
Important to note that this repeated failure upon `setContent()` immediately followed a share fail due to this https://github.com/the-grid/androidapp/issues/361#issuecomment-190228445
Likely related and something has left Ed in an unstable state.

**Comment by nickvelloff** [comment]
OK I think this is a dupe of https://github.com/the-grid/ed/issues/87. 
Currently it is very easy to keep typing after a share and overwrite the servers replacement of the placeholder block.
App then receives an item update notification and writes the placeholder back over the replaced block, and the editor "breaks" and throws the above for all subsequent `setContent()` attempts. 

I'll leave this open for reference but feel free to close if you like.

**Comment by forresto** [comment]
This good with 0.6.2? @nickvelloff

**Comment by nickvelloff** [comment]
@forresto Confirmed. No error!!! :fireworks: :+1:
