### ISSUE TITLE
iOS - Double-tap spacebar does not insert period (.)

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#109]
This makes editing on iOS particularly cumbersome because without it you have multiple clicks just to insert a period. 
Filed upstream: https://github.com/ProseMirror/prosemirror/issues/234

**Comment by forresto** [comment]
Hmm... double-space→. for everybody?

**Comment by nickvelloff** [comment]
Hmmm indeed. Could it be a `config` option perhaps?

**Comment by nickvelloff** [comment]
Basically Optional, Defaults to `false`
`config.doubleSpaceToPeriodEnabled = true`

**Comment by nickvelloff** [comment]
maybe overloaded the constructor and can accept an optional param config object.
`edMount(initialContent: Object, config:Object? = null)`

**Comment by forresto** [comment]
I think I'll just sniff `iThing` like I'm doing with the fixed menu hack.

**Comment by nickvelloff** [comment]
Heh or that :smile_cat:

**Comment by forresto** [comment]
@mario Marijn's hint https://github.com/ProseMirror/prosemirror/issues/234#issuecomment-209915136

Commands need to be added like this: https://github.com/the-grid/ed/blob/master/src/commands/index.js#L6 ... with iOS sniff :nose:.

**Comment by nickvelloff** [comment]
Added as blocker after review with the team. Even the most liberal on the release front think it is unusable.
