### ISSUE TITLE
iOS - Text block focus shifts text over widget bounds

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#110]
I'm not clear is this is an upstream issue because there are no widgets upstream.
Off the top of my head, I would guess an inserted `<p>` has something to do with it. 
Secondarily, the incorrect resulting scroll position _may be_ resolved by fixing the root cause of this.

![ed-text-shift](https://cloud.githubusercontent.com/assets/885369/13478757/728803b2-e087-11e5-89f9-75d23eca4ede.gif)

**Comment by nickvelloff** [comment]
Also in the video notice pressing a key _fixes_ it...

**Comment by forresto** [comment]
If there isn't an error it's probably a :racehorse: with widget positioning. Hopefully #88 (depends on next PM) will get rid of all of that complexity.
