### ISSUE TITLE
Mobile toolbar styling pass

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#118]
Looks a bit off still when flowing into two rows:
<img width="517" alt="screen shot 2016-03-10 at 11 41 03" src="https://cloud.githubusercontent.com/assets/115381/13667084/1781e436-e6b5-11e5-89ad-855f1472f2eb.png">

**Comment by forresto** [comment]
![screen shot 2016-03-12 at 11 40 15 am](https://cloud.githubusercontent.com/assets/395307/13724124/114999e8-e849-11e5-9791-82d42f13642c.png)

**Comment by hannesstruss** [comment]
:raised_hands: :bow:

**Comment by nickvelloff** [comment]
@forresto I had an idea that may be terrible, but want to run past you.
Would it make any sense to try to just "mirror" the toolbar in another html view by connecting it js somehow, thereby allowing native apps (specifically iOS) to fix it in a view to avoid the jittery issues?

If we were able to pull it off, we may not ever need the native toolbar bridge. 
Just a thought.
