### ISSUE TITLE
Inserting placeholder blocks triggers autosave

### ISSUE THREAD

**Issue by JohnRandom** [the-grid/ed#120]
It seems like inserting placeholder blocks into the document triggers a `change` and subsequent `autosave` event from the post editor. This is a problem, since inserting placeholder blocks usually precedes saving it anyway. This usually means that the item is saved and fetched more than necessary and may cause more issues down the road. I would like to suggest, that we either don't send external `autosave` or `change` events on data management related editor API calls, like `insertPlaceholders`, `setContent`, etc. or instead equip them with a `{ silent: true }` option.

I realise that the events are needed for the internal editor management, so my suggestion only relates to external `change` and `autosave` events.

**Comment by nickvelloff** [comment]
@JohnRandom FWIW @hannesstruss and I both migrated away from the debounced `autosave` and manage that app side. I found I ended up needing more fine grained control, and predict that need will only increase over time. 
Still I think your suggestion is a good one, just a heads up :+1:

**Comment by JohnRandom** [comment]
@nickvelloff how exactly did you move away from that, without relying on the `change` or `autosave` event?

**Comment by nickvelloff** [comment]
@JohnRandom I just use `change`, and not `autosave`. This change would be good either way and not break anything on my end. My comment was not to disagree with the proposal, just a related thing we came across.

**Comment by JohnRandom** [comment]
@nickvelloff I understand that. This issue will yield the same result, whether or not you use `change` or `autosave`, though.

**Comment by nickvelloff** [comment]
True. :+1:

**Comment by forresto** [comment]
No extra change event as of 0.5.0 #107
