### ISSUE TITLE
placeholder cancel ui and event

### ISSUE THREAD

**Issue by JohnRandom** [the-grid/ed#121]
It's very easy to accidentally delete a placeholder with backspace. This doesn't, however, stop or cancel the upload and at some point the upload will finish. Due to the way the editor updates new content, the successfully shared image won't appear until the next reload.

It seems that the expected behaviour would be, that placeholder blocks should not be deleted with a backspace key stroke, but rather have a `cancel` button that will emit a proper event and leave the app to clean it up. This if course would also mean, that `setContent` needs to identify and remove existing placeholders that are do longer exist.

**/cc** @nickvelloff @hannesstruss @forresto @marsch

**Comment by nickvelloff** [comment]
+1 I agree I'm on this same issue as well.

**Comment by forresto** [comment]
I'll prioritize the cancel button and event. 

Suppressing delete is PM guts territory, and needs experimentation. Maybe a confirmation would be better than just blocking delete.

**Comment by JohnRandom** [comment]
Confirmation would only make sense, when the uploading is still in progress (and sharing cancellation is implemented) or when we can cancel share jobs. Otherwise we cannot stop the process, even if the user confirms it.
