### ISSUE TITLE
ContentBlock schema: should Ed generate IDs?

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#122]
It looks like Ed produces blocks without `id`, but apidocs schema says blocks always have one: https://github.com/the-grid/apidocs/blob/master/schemata/contentblock.yaml

Should Ed adhere to that and generate IDs for blocks it creates?

Ed also doesn't set `html` on placeholders, even though apidocs mark it non-optional. `html` on placeholders doesn't really make sense, so maybe that's a case for changing the docs.

cc @bergie

**Comment by bergie** [comment]
Yep, docs are out of date. Placeholder HTML shouldn't be required

**Comment by forresto** [comment]
@bergie what about tracking ids for html blocks? It has always been a boondoggle because of all of the complexity with splitting, merging, changing block types. So Ed ignores them.

**Comment by forresto** [comment]
Ed doesn't track ids on non-media blocks.
