### ISSUE TITLE
position of meta editors on small screens

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#126]
Fixed doesn't work with iOS keyboard #101, but this relative popover is off of small screens :-1: 

![screen shot 2016-03-15 at 4 35 27 pm](https://cloud.githubusercontent.com/assets/395307/13793242/4eb63a54-eacc-11e5-9254-90b419746279.png)

**Comment by forresto** [comment]
![screen shot 2016-03-17 at 11 50 51 am](https://cloud.githubusercontent.com/assets/395307/13852055/e10f5294-ec36-11e5-80a0-cd6a500ebf6e.png)

**Comment by nickvelloff** [comment]
if :point_up: is working now you are my hero Forrest
