### ISSUE TITLE
Which files do I have to provide for widgets, e.g. ced?

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#128]
Displaying `ced` widgets fails with `Unable to open asset URL: file:///android_asset/posteditor/node_modules/@the-grid/ced/editor/index.html`. Is there a general rule for which files have to be supplied? I'd rather avoid linking all of `node_modules` into my tree. Currently, I'm only using `ed.js` (and `ed.js.map`).

cc @nickvelloff

**Comment by forresto** [comment]
dist/node_modules that makes it to npm is what you need. They are whitelisted in [package.json .widgets](https://github.com/the-grid/ed/blob/347b04de2d43b074a400af90db6b34b4bc83573d/package.json#L39) and copied in the build process. You can copy everything in dist/.

**Comment by hannesstruss** [comment]
Thanks! :bow:
