### ISSUE TITLE
validate urls

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#129]
Show when URL isn't valid (and suppress changes (?)) for those inputs.
- [x] sharing url from above fold
- [ ] attribution link editors

**Comment by bergie** [comment]
Yep, needs to be done when sharing URLs, as well as when editing metadata:

<img width="404" alt="screen shot 2016-03-18 at 20 47 07" src="https://cloud.githubusercontent.com/assets/3346/13890230/a80a28c4-ed4a-11e5-8f31-7314b98ab108.png">

**Comment by forresto** [comment]
TextareaAutosize component has a `validator` function  prop now.
![validator](https://cloud.githubusercontent.com/assets/395307/15561998/3e454cb6-22c9-11e6-8165-0023068a1925.png)
