### ISSUE TITLE
iOS - Sticky toolbar does not appear in versions > 0.4.7

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#134]
I tested different versions and this seems to have been introduced in version `0.5.0`. A caching issue caused me not to see it until just now on the released TestFlight version.

<img width="487" alt="screenshot 2016-03-20 18 30 43" src="https://cloud.githubusercontent.com/assets/885369/13908885/e0d3acc2-eec9-11e5-8bba-d080e9068395.png">

**Comment by forresto** [comment]
- BREAKING -- options.[menuBar|menuTip] made camelCase

Catch that item in Changes for 0.5.0? @nickvelloff

**Comment by nickvelloff** [comment]
Oops! My bad. 😨
