### ISSUE TITLE
"Remove Block" switch `window.confirm()` to proper UI

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#138]
There are no js errors thrown.
![ed-remove](https://cloud.githubusercontent.com/assets/885369/13964110/7331e4f6-f025-11e5-81b3-29614416abc0.gif)

**Comment by nickvelloff** [comment]
Ed `v0.7.1`

**Comment by forresto** [comment]
`window.confirm()` was in there as placeholder. Will switch to proper UI.

**Comment by nickvelloff** [comment]
:bow:
