### ISSUE TITLE
updatePlaceholder progress overwritten by stale placeholder.metadata

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#149]
During an image upload the following can happen when continuing to edit the item.
- Periodically we save the item as the user edits. 
- This causes item update notifications to arrive from API
- We fetch the item and `setContent()`
- That item data generally will contain stale `placeholder.metadata` progress info
- Causes `ed` to overwrite item progress to an incorrect previous value until the app sends another progress `updatePlaceholder`, which may not happen if it's finished uploading leaving the UI in an incorrect state

Possible solutions
- Don't store `PUT` placeholder.metadata (think we need that for persistence)
- Nuke placeholder.metadata incoming on app (hacky)
- Ignore placeholder.metadata if progress < currentProgress (less but still hacky)
- ???

**Comment by forresto** [comment]
Before `setContent()`, app could strip blocks other than ones that were placeholders and are now "real."

**Comment by nickvelloff** [comment]
OK.
It's a good topic for https://github.com/the-grid/chrome-mobile-stories/pull/24 - I'll add it @hannesstruss

**Comment by nickvelloff** [comment]
@forresto so when the API turns

``` JSON
{
    "type" : "text",
    "html" : "<p>Aaaa<\/p>"
  }
```

into

``` JSON
{
    "measurementHash" : "f031b12008c584808ff40f469575aa6b",
    "measurementVersion" : 16,
    "id" : "6e599e83-7128-4a44-962d-6754d6b98ada",
    "created_at" : null,
    "src" : null,
    "html" : "<p>Aaaa<\/p>",
    "type" : "text",
    "updated_at" : null,
    "item" : "5024b195-75d6-4ee0-b54b-fc45e8bf58bb",
    "metadata" : {
      "starred" : true,
      "publisher" : {

      },
      "source" : "5024b195-75d6-4ee0-b54b-fc45e8bf58bb"
    }
  }
```

should that be stripped out, or delivered with `setContent()`?

**Comment by nickvelloff** [comment]
I think you must be ignoring blocks without ids coming back from API because how would you map them anyway (short of pattern matching `html`).

**Comment by forresto** [comment]
setContent's merging strategy only considers new placeholders, new media blocks, and placeholders changed to media blocks. https://github.com/the-grid/ed/blob/90f380417afc257dd4598bfe30b64c68a19f2838/src/ed.js#L377

**Comment by nickvelloff** [comment]
A _Swiftplanation_ for our meet up work on this @hannesstruss 
Doing inbound data mutation is a sketchy separation of concerns IMO but here it is.

``` Swift
/*
     Inbound content blocks are compared with existing content blocks
     if existing block == placeholder && matching incoming block !placeholder then
     update that block
    */
    func setLocalContent(inboundContent inboundContent: JSON) {
        getContent { result in
            switch result {
            case let .Success(currentContent):
                let current = currentContent.arrayValue
                    .filter { return $0["type"].stringValue == "placeholder" }
                    .map { return $0["id"].stringValue }

                let inbound = inboundContent.arrayValue
                    .filter { return $0["type"].stringValue != "placeholder" }
                    .map { return $0["id"].stringValue }

                let intersectingSet = Set(current).intersect(Set(inbound))

                let content = inboundContent.arrayValue
                    .filter { return intersectingSet.contains($0["id"].stringValue) }

                let json = JSON(content)
                guard let contentString = json.rawString() else { return }
                let js = "window.ed.setContent(\(contentString));"
                self.webView.evaluateJavaScript(js, completionHandler: nil)
            default: break
            }
        }
    }
```

**Comment by nickvelloff** [comment]
Also thanks @forresto :bow: 
We'll work through this a bit more at the meetup and see where we land. Plan is to diagram the whole app <--> ed lifecycle and poke holes so we can do it the same way across apps

**Comment by hannesstruss** [comment]
@nickvelloff I don't listen to `item_updated` GCM messages at all in the editor, only for `completed_job`.

**Comment by nickvelloff** [comment]
@hannesstruss I tried that as well. Even if you only fetch the item on `completed_job` there are still cases things go wrong like:
Item completes measuring one image while another image upload is in progress.

**Comment by nickvelloff** [comment]
@hannesstruss let's just reference this in our flow discussions. One thing I found after trying quite a few things is the combination of listening to `item_updated` + using `setCoverPreview` gives super fast _edit-ability_ of uploaded images. Just something to talk about later. 

Closing for now as this is an app concern.
