### ISSUE TITLE
iOS webview not compatible with menu hacks

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#15]
Updating to today's PM gives

> Uncaught TypeError: (0 , _prosemirrorSrcMenuMenu.commandGroups) is not a function

so @d4tocchini will need to rehack that for us to update PM.

**Comment by d4tocchini** [comment]
i fixed this locally, will push...

**Comment by forresto** [comment]
Getting this on load with PM 0.1.1 pushed to master 

> Uncaught TypeError: (0 , _command.defineCommand) is not a function

**Comment by d4tocchini** [comment]
yes, this is expected, tons has changed w/ commands + menu in latest PM

will fix...

**Comment by forresto** [comment]
Is this fixed?
