### ISSUE TITLE
Typing while setContent() in progress (regardless of payload) can cause erroneous sync/merge

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#157]
Due to a bug on the **iOS app** I identified something that _may_ be a bug in the ed merge/sync during `setContent`.

I fixed the bug, but this could affect other clients and also may be an issue when `setContent()` get called frequently due to legitimate cases such as many uploaded images and URL shares.

The bug I had was instead of **not** calling `setContent()` when (after sanitizing incoming data per the rules we discussed) I called it with and empty array `[]` as the payload. 

Then while I was typing, characters I typed would occasionally get inserted in the wrong place, often at the beginning of the string. This would happen at the time `setContent` as called with an empty array.

This no longer an issue for me (presumably) as I no longer call `setContent` unless there are applicable changes, but it may be something want to investigate. I'm not clear if the same thing could happen even with legitimate content updates, as they happen so rarely it is very difficult to test in my environment.

**Comment by forresto** [comment]
I have something in demo.js for :monkey: testing this.

But it has been a constant issue that might not go away until we have OT APIs.

**Comment by nickvelloff** [comment]
@hannesstruss This should be part of our Ed lifecycle story, adding to agenda.
Related to https://github.com/the-grid/ed/issues/149#issuecomment-203739830 in that _for now_ we likely only want to `setContent` as infrequently as possible.

**Comment by forresto** [comment]
Current `fixSelection` is halfassed. 

I need to keep track of how the selection should change through various mutations that can happen with `_setMergedContent` (which happens after the placeholder merge with `ed.setContent`).

eg Changing a url to a `placeholder` media block (above the current selection) changes the selection head and anchor by `- url.length - 1`. Splicing multiple placeholders in changes those positions by # of placeholders. (Media widgets are empty div leaf nodes that have `nodeSize` 1.)

**Comment by forresto** [comment]
Should be good in 0.12.0 😄
