### ISSUE TITLE
Mobile: Fold UI needs styling

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#159]
See screenshot below. Also, since we don't have the floating toolbar on mobile, the "Link to an image..." text/button is confusing.

<img width="513" alt="genymotion_-_google_nexus_4_-_5_0_0_-_api_21_-_768x1280__768x1280__320dpi__-_192_168_57_101" src="https://cloud.githubusercontent.com/assets/115381/14347684/a55a216a-fcb8-11e5-95c9-4192d981658e.png">

**Comment by forresto** [comment]
Good hit list. A bunch of this will change with the new post flow #141 coming next.

**Comment by forresto** [comment]
![screen shot 2016-04-07 at 5 41 05 pm](https://cloud.githubusercontent.com/assets/395307/14367796/10649f92-fce8-11e5-81a9-53fed0062f76.png)

**Comment by hannesstruss** [comment]
Nice! ✨
