### ISSUE TITLE
Add API for toolbar

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#173]
In order to present toolbars natively on Android/iOS, we need an API in Ed that allows us to
1. See which toolbar elements should be shown
2. Which state these elements are in
3. Be notified if something changes about 1. or 2.
4. Tell Ed that a button was pressed/something was selected
#### Considerations:
- We have regular buttons (bold, italic, list...) that can be `enabled`, `active`, `disabled` and `gone` (also `active+disabled`? If not, we should ignore that case)
- We have a selector for headline type (`h1`, `h2`, `h3`, `plain`) that can be `enabled` or `disabled` 
#### Proposal (WIP, feedback needed!):
- Add `onToolbarChanged: function(ToolbarDefinition) { ...` event hook to Ed config which is called once initially and then once needed (see 3. of list on top)
- `ToolbarDefinition` could look like

```
{
  headlineState: "enabled" | "disabled" | "gone",
  headlineSelection: "1" | "2" | "3" | "plain",
  <buttonId>: "enabled" | "active" | "disabled" | "gone", ...
}
```

(Question is whether to special case headline, or come up with a generic solution. I'd favor special casing, as a generic solution would probably require a more deeply nested object structure.)
- Add `ed.onToolbarButtonClicked(buttonId)` and `ed.onHeadlineTypeSelected(String)`

**Comment by hannesstruss** [comment]
In addition to the hook being called once initially, we could also add `ed.getToolbarState()`.

**Comment by forresto** [comment]
I don't think there is a distinction between disabled and gone.

I wouldn't special-case headings. Seems like keeping it flat lets apps try different ways to present those.

**Comment by hannesstruss** [comment]
> I don't think there is a distinction between disabled and gone.

true, let's drop disabled (or drop gone and have "disabled" instead, either way is fine for me)

> I wouldn't special-case headings. Seems like keeping it flat lets apps try different ways to present those.

Yeah, I had a similar discussion with @nickvelloff regarding the headlines. My point was that having `{"h1": "active", "h2": "enabled", ...}` in the structure would allow inconsistent states – but probably no big deal in practice. I'm fine with no-special-case too.

**Comment by forresto** [comment]
This is what I have so far:

```
{
  "strong:toggle": "inactive",
  "em:toggle": "inactive",
  "link:unset": "active",
  "link:set": "inactive",
  "paragraph:make": "inactive",
  "heading:make1": "active",
  "heading:make2": "inactive",
  "heading:make3": "inactive",
  "bullet_list:wrap": "disabled",
  "ordered_list:wrap": "disabled",
  "blockquote:wrap": "disabled",
  "lift": "disabled",
  "ed_upload_image": "inactive",
  "undo": "inactive",
  "redo": "disabled"
}
```

**Comment by forresto** [comment]
If you want more info and default sorting, this could be an array of objects.

(The object actually has the default order, but objects don't have order. 🖖)

**Comment by forresto** [comment]
@nickvelloff @hannesstruss you can't call this a blocker then not implement it... https://github.com/the-grid/ed#commands

**Comment by nickvelloff** [comment]
@forresto completely fair. will get it done.
