### ISSUE TITLE
Android: No change events fired (mid-word) when using keyboard with Autocomplete

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#175]
Tested with 0.10.1. Issue might be upstream.

**Comment by forresto** [comment]
AFK, but I don't see how this wouldn't be upstream.

**Comment by forresto** [comment]
I'm seeing uncaught errors on prosemirror.net as well.
https://github.com/ProseMirror/prosemirror/issues/304

**Comment by forresto** [comment]
Despite the uncaught errors PM-side and lack of change events, editing seems to work fine now and `getContent()` returns the expected content.

**Comment by forresto** [comment]
Actually, I'm not seeing the uncaught errors in Ed's demo. Change events are firing. @hannesstruss is this a webview-only issue?

Maybe prosemirror.net isn't on PM 0.6.1 yet.

**Comment by hannesstruss** [comment]
@forresto yeah, editing works fine indeed! :) Doing some testing wrt. pm.net, chrome vs. webview now.

**Comment by hannesstruss** [comment]
@forresto Tested:
- Webview on https://the-grid.github.io/ed/ ❌ 
- Android Chrome on https://the-grid.github.io/ed/ ❌ 

In both cases I get 1-3 change events, but then nothing anymore. No errors are being logged apart from a "You're using a minified copy of the debug version of React"

Can I attach change handlers to an initialized PM instance? Not sure how to test pm.net otherwise.

**Comment by forresto** [comment]
@hannesstruss `pm.on('change', function () {console.log('change')})` works on prosemirror.net

At least in Chrome, both are fine on my N7. I don't see `change` events while typing a word and it is underlined, but on space (or autocomplete) I see two (I guess word change, then adding space). Is that not what you're seeing?

I thought your bug must be an uncaught error breaking Ed, but...?

**Comment by hannesstruss** [comment]
@forresto You're right, that's the behavior I'm seeing too. Might still cause unsaved changes when closing the editor before "finishing" a word by pressing space or autocomplete.

**Comment by forresto** [comment]
Yeah, `getContent()` doesn't have "uncommitted" word. But other than that, we're pretty :ok_hand:

**Comment by forresto** [comment]
But, the underlined word is committed and available if Editable is blurred. So there should be some workable hack to do that before publish / save.

**Comment by forresto** [comment]
@hannesstruss can we close this?

**Comment by hannesstruss** [comment]
Yep! 🙌
