### ISSUE TITLE
New styling huge on mobile

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#178]
0.10.3

<img width="559" alt="genymotion_-_google_nexus_4_-_5_0_0_-_api_21_-_768x1280__768x1280__320dpi__-_192_168_57_101" src="https://cloud.githubusercontent.com/assets/115381/14622216/349d5e42-057d-11e6-8a24-453293c2cbc0.png">

**Comment by forresto** [comment]
Threw in a max rule to shrink that chunky
![screen shot 2016-04-19 at 9 40 35 am](https://cloud.githubusercontent.com/assets/395307/14641153/dee65eae-0612-11e6-963b-e43efe166576.png)
