### ISSUE TITLE
Too much padding on mobile?

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#183]
or expected behavior? (0.10.5)

cc @narrowdesign 

<img width="517" alt="genymotion_-_google_nexus_4_-_5_0_0_-_api_21_-_768x1280__768x1280__320dpi__-_192_168_57_101_and_slack" src="https://cloud.githubusercontent.com/assets/115381/14664024/c875dc1c-067b-11e6-812c-33ebbf552938.png">

**Comment by forresto** [comment]
This was reworked in #226
