### ISSUE TITLE
iOS - Image upload above fold styling needs massage

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#188]
(ignore the iOS nav and such its V2 klunkery)
<img width="487" alt="screenshot 2016-04-22 01 31 26" src="https://cloud.githubusercontent.com/assets/885369/14736155/04765fac-082a-11e6-9d92-35f643a3f3a5.png">

**Comment by nickvelloff** [comment]
cc @narrowdesign

**Comment by forresto** [comment]
Ditched in 0.12.0
