### ISSUE TITLE
"Upload Cover Photo" does not seem to trigger onShareFile 

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#190]
cc @marsch @narrowdesign 

`onShareFile` starts the whole image upload flow in the clients, and the "Upload Cover Photo" button doesn't seem to trigger it.
<img width="487" alt="screenshot 2016-04-23 01 06 47" src="https://cloud.githubusercontent.com/assets/885369/14760176/3a97aa10-08f1-11e6-9c51-4e59ea40c83a.png">

**Comment by forresto** [comment]
@marsch @d4tocchini could you tell @nickvelloff and me how this should work?

**Comment by forresto** [comment]
@nickvelloff please stick with 0.10.7... 

0.11.0 should have been tagged beta / experimental / [wtf](https://github.com/the-grid/ed/blob/106d83ed74fd424def7ff946525b4911e9471376/src/ed.js#L342).

**Comment by nickvelloff** [comment]
@forresto Will do. The release version is `0.10.1`, as it was the latest at the time (that was not 0.11.0)

**Comment by forresto** [comment]
@nickvelloff see https://github.com/the-grid/ed/blob/master/CHANGES.md#0104---2016-04-19 ... API is going to reject image and article metadata changes b/c Ed wasn't writing them to `block.html`.

**Comment by nickvelloff** [comment]
@forresto oh no... ok thanks for the heads up. I'll head back to iOS v1 and get a release in the queue with `0.10.7`

**Comment by forresto** [comment]
To be designed in #71
