### ISSUE TITLE
Media block description not shown in editor

### ISSUE THREAD

**Issue by bergie** [the-grid/ed#192]
It seems media block descriptions are not shown by the editor:

![screenshot_20160502-120431](https://cloud.githubusercontent.com/assets/3346/14952157/51b2549c-105e-11e6-8245-a4a83374846d.png)

The description is shown in the cards correctly:

![screenshot_20160502-120420](https://cloud.githubusercontent.com/assets/3346/14952162/5e944224-105e-11e6-919d-40b59eb36ff4.png)

It is also shown (and editable) in the old editor:

![screenshot_20160502-120759](https://cloud.githubusercontent.com/assets/3346/14952178/a5fcd586-105e-11e6-9538-5ab9628f7959.png)

**Comment by forresto** [comment]
Seems to work here: http://the-grid.github.io/ed/#fixture could it be a webapp issue? @JohnRandom

**Comment by bergie** [comment]
This was on the Android app. Will try webapp and iOS next

Cc/ @hannesstruss

**Comment by bergie** [comment]
Confirmed. Description not shown on Android, but is shown in web and iOS apps. Moving to appropriate repo...
