### ISSUE TITLE
Handle unsalvageable images

### ISSUE THREAD

**Issue by bergie** [the-grid/ed#195]
If media cover has `unsalvageable: true`, then that means the original image has gone 404 or is in some other way invalid.

It would be great for the media editor to be able to show this and allow user to replace/remove the image.

Same goes for author avatars.

**Comment by bergie** [comment]
The UI we have in the live version seems to mostly cover this, but might be nice to show something else than the default "broken image" icon

<img width="908" alt="screen shot 2016-05-17 at 18 09 39" src="https://cloud.githubusercontent.com/assets/3346/15329867/a20fb986-1c5a-11e6-9ec0-71daea53d33d.png">

**Comment by forresto** [comment]
`onRequestCoverUpload` ready in 0.13.0 ... I'll make a prominent button to trigger that event to address this story.

**Comment by forresto** [comment]
![screen shot 2016-05-31 at 3 46 00 pm](https://cloud.githubusercontent.com/assets/395307/15688346/979ffa22-2747-11e6-8985-80d589e001db.png)
