### ISSUE TITLE
Media block title changes not reflected in getContent()

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#196]
Originally reported in https://github.com/the-grid/androidapp/issues/486

Steps:
1. Open item with media block above fold
2. Change media block title
3. Inspect result of `getContent()`, still returns old value for title

http://hs-random.s3.amazonaws.com/title-doesnt-update.mov

**Comment by forresto** [comment]
@hannesstruss can you reproduce it on https://the-grid.github.io/ed/ ??? I can't:

![screen shot 2016-05-17 at 12 48 55 pm](https://cloud.githubusercontent.com/assets/395307/15331117/c159afae-1c2d-11e6-9756-3c781cb141e4.png)

**Comment by hannesstruss** [comment]
Fixed in 10.7
