### ISSUE TITLE
Cursor Jumps to Start of Line Break

### ISSUE THREAD

**Issue by webbjordy** [the-grid/ed#201]
**Description**
Cursor jumps to beginning of line. This happens after an image is uploaded and then the user continues to type in the editor.

**Steps to Reproduce**
Start typing in the webapp editor
Upload an image
Continue typing in the editor

**Expected Results**
Cursor stays at the end of the line to type as normal

**Actual Results**
Cursor jumps to the beginning of the line break

**Platform**
Webapp v2

**Comment by webbjordy** [comment]
cc @nickvelloff

**Comment by forresto** [comment]
The fix is smarter merging (#197), working on in current push.
