### ISSUE TITLE
Add label to Author & Publisher dropdown

### ISSUE THREAD

**Issue by netlemur** [the-grid/ed#203]
![screen shot 2016-05-24 at 16 14 55](https://cloud.githubusercontent.com/assets/773681/15507174/c78e1b24-21ca-11e6-9417-c08de6f0d74c.png)

After entering text for Author and Publisher it's not clear anymore which field was for which content – it only shows 'Name'

Maybe adding "Author Name", "Publisher Name" as label or something similar could help?

**Comment by forresto** [comment]
![author, publisher label](https://cloud.githubusercontent.com/assets/395307/15562244/95b12b76-22cb-11e6-843a-5002088676eb.png)
