### ISSUE TITLE
iOS - Layout issues

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#208]
iOS 9, Ed v0.12.2

Opening an item to edit looked like this:
<img width="487" alt="screenshot 2016-05-26 00 16 38" src="https://cloud.githubusercontent.com/assets/885369/15566723/4b98a6ca-22d7-11e6-9dfe-ed1a2eb26e53.png">
After clicking "Make full post" it looked like this:
<img width="487" alt="screenshot 2016-05-26 00 09 58" src="https://cloud.githubusercontent.com/assets/885369/15566535/6f9b49ac-22d6-11e6-80dd-a6b726723253.png">
I clicked the arrow (top left) and it flipped and looked like this:
<img width="487" alt="screenshot 2016-05-26 00 10 04" src="https://cloud.githubusercontent.com/assets/885369/15566532/6f8cbd4c-22d6-11e6-85fd-aed90c89bfcc.png">
Then flipped back again:
<img width="487" alt="screenshot 2016-05-26 00 10 14" src="https://cloud.githubusercontent.com/assets/885369/15566531/6f8beeb2-22d6-11e6-837f-d6c847167dd1.png">
Click again the toolbar appeared (cursor not inserted):
<img width="487" alt="screenshot 2016-05-26 00 10 25" src="https://cloud.githubusercontent.com/assets/885369/15566533/6f8cde80-22d6-11e6-8ce5-4a5018ac22ca.png">
The top scroll view:
<img width="487" alt="screenshot 2016-05-26 00 10 54" src="https://cloud.githubusercontent.com/assets/885369/15566534/6f959c0a-22d6-11e6-90e5-c46f53a874db.png">

**Comment by forresto** [comment]
Left and right are undo / redo.

Layout issues... are those big local images or have they gone through imgflo? I'm having trouble reproducing. Might be that a timeout to relayout would bandaid it, but that doesn't fix the underlying issue.

**Comment by forresto** [comment]
That layout is ~0.2ms when there are no changes, so I think it's safe to do in an interval as a hack for when things get off.

**Comment by nickvelloff** [comment]
Those are all imgflo, and older posts. Even local I size down according to screen dimension so I don't send huge stuff over the bridge.

**Comment by forresto** [comment]
@nickvelloff See if the loop in 0.12.3 fixes this.

**Comment by nickvelloff** [comment]
@forresto this is fixed, though blinky blinky as you might imagine.

**Comment by forresto** [comment]
@nickvelloff does it settle in a couple seconds?

**Comment by nickvelloff** [comment]
@forresto yup, it does
