### ISSUE TITLE
What is "Make Full Post" and why is it the first button?

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#209]
Is this a temp thing? 

<img width="487" alt="screenshot 2016-05-26 00 16 38" src="https://cloud.githubusercontent.com/assets/885369/15566897/3ca69392-22d8-11e6-81eb-5810cb24c3b0.png">

**Comment by forresto** [comment]
Yeah, placement is. In the new flows doc I proposed that it will show up after content, after person starts adding blocks. Alternatively, it could be persistent below the content (while there is no fold `hr`).

**Comment by forresto** [comment]
See if 0.12.3 solves this.
