### ISSUE TITLE
Construct with configuration 

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#21]
Can we construct the editor object with a configuration? 
3 come to mind:
1. Do or don't use toolbar 
2. Auto save enabled
3. Auto save frequency

**Comment by forresto** [comment]
How to use config so far: https://github.com/the-grid/ed/blob/8829113d2aadedb3d8c1d6ac1fa9d61c80ead4a8/demo/demo.js#L15-L22 ... will document in readme.

One of the options is `onChange` function which gets hit on every change. It's up to the surrounding app to debounce then get `ed.content`.

**Comment by forresto** [comment]
Docs: https://github.com/the-grid/ed#use
