### ISSUE TITLE
Scroll positions leave cursor character insertion hidden

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#211]
iOS 9 Ed 0.12.3
![ed-0 12 3](https://cloud.githubusercontent.com/assets/885369/15600892/b44b25e2-23a1-11e6-920a-fc7f1b38bf92.gif)

**Comment by forresto** [comment]
Hmm... how about a blank `p` focused and ready for commentary above the media block? If content[0] is media. Combined with #204 should be smoother.

**Comment by forresto** [comment]
@nickvelloff See if this pain is gone with 0.12.4 🎩

**Comment by nickvelloff** [comment]
Fixed. 🙇
