### ISSUE TITLE
iOS - After double spacebar click, should toggle back to caps

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#215]
iOS 9, Ed 0.12.5
No idea if this is possible, but is a default behavior on iOS if it can be done.

**Comment by nickvelloff** [comment]
OK this behaves as expected in latest Ed. I'll keep an eye out.

**Comment by forresto** [comment]
_stackoverflow doesn't even_

**Comment by nickvelloff** [comment]
👆🤔
