### ISSUE TITLE
Upload Image Button disappears after cancel upload

### ISSUE THREAD

**Issue by marsch** [the-grid/ed#219]
![button_bug](https://cloud.githubusercontent.com/assets/179281/15653199/b90bdc74-268b-11e6-9450-6e59794132b0.gif)

think that behavoir is not intended, at least am a bit confused, that the button disappeared

**Comment by forresto** [comment]
It does come back when you type in the post, but I can take out the immediate hide.

**Comment by bergie** [comment]
There was some trick we used in V1 to detect cancelled upload dialog, but I don't remember what it was.

Something along the lines of: http://stackoverflow.com/questions/4628544/how-to-detect-when-cancel-is-clicked-on-file-input

**Comment by forresto** [comment]
@bergie I think we gave up on that in v1. I can just listen to the content change, not click ☝️
