### ISSUE TITLE
"Author" → "Credit"

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#221]
Anybody opposed to changing "Add Author" to "Add Credit"? 

"Author" feels weird on images and videos.

![screen shot 2016-05-31 at 4 52 01 pm](https://cloud.githubusercontent.com/assets/395307/15690125/092db708-2750-11e6-9cf8-3f4a66be5fe0.png)

**Comment by nickvelloff** [comment]
Personally I like the idea.
