### ISSUE TITLE
video block html output

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#232]
@bergie what format does API expect html of `video` blocks?

cover image, title, description, video embed or iframe?

**Comment by marsch** [comment]
@forresto this? https://github.com/the-grid/schema/blob/master/spec/types.coffee

**Comment by nickvelloff** [comment]
@bergie 📞 "hello?"

**Comment by forresto** [comment]
@marsch when Ed changes some block types' metadata, it also needs to store that metadata in the html string, since API (Caliper) will overwrite metadata with properties in the html string.

Video metadata changes are getting reverted by API, but it isn't documented how to save the block to avoid that.

**Comment by bergie** [comment]
No particular magic here, it is all dependent on what attributes html-flatten extracts from the HTML. Looking [at the source](https://github.com/the-grid/html-flatten/blob/master/index.coffee#L198), you can see the different cases relevant to videos:
- `iframe`: no good place for title or description, so they come from metadata
- `video`: no good place for title or description, so they come from metadata
- `figure`: caption comes from `figcaption`, we may also have title handling once the-grid/html-flatten#35 is done. Before that, metadata

**Comment by nickvelloff** [comment]
@bergie this doesn't sound like an actionable answer.

**Comment by forresto** [comment]
API fix live 👍
