### ISSUE TITLE
indicate drop-zones

### ISSUE THREAD

**Issue by marsch** [the-grid/ed#235]
I really like the new Drop-Features, but as a user am a bit confused that I don't see an indicator for the 2 different dropzones. IMO there must be something like a hover state when a file is dragged over a dropzone

![drop-indicator](https://cloud.githubusercontent.com/assets/179281/15970465/f9240104-2f34-11e6-8833-7bf5ee12ae32.gif)

**Comment by forresto** [comment]
ugly but 💣 
![ed-drop-indicator](https://cloud.githubusercontent.com/assets/395307/16320601/9c5f7372-3966-11e6-8005-65100ccc2300.gif)
