### ISSUE TITLE
Block metadata editor needs mobile love

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#236]
Currently it's quite cumbersome to edit block metadata, as not much of the UI fits on one screen:

![pnhb2nnm0x](https://cloud.githubusercontent.com/assets/115381/15992686/2f9c78d0-30d2-11e6-91ac-6ec65d26c7b5.gif)

**Comment by bergie** [comment]
It might help if we fade out the editor toolbar when the metadata widgets are in focus

**Comment by hannesstruss** [comment]
Once toolbar is native it'll probably hide when scrolling or something like that. Cause of this is rather the buttons being placed below each other.
