### ISSUE TITLE
updatePlaceholder - don't save to content

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#237]
Need to make sure this is OK with @marsch @nickvelloff @hannesstruss. We don't want placeholder status/progress/failed saved to API, so it should work like setCoverPreview: cached by Ed, not saved to content.

**Comment by hannesstruss** [comment]
@forresto shame on me, I haven't implemented placeholder status or cover preview yet. What's the status quo?

**Comment by forresto** [comment]
Now, hitting `ed.updatePlaceholder(id, {status: 'workin'})` will put that `status` in that block's metadata. Thinking that we don't want to save that to content/API though.

**Comment by forresto** [comment]
So for @hannesstruss , that's more state to deal with caching.

**Comment by hannesstruss** [comment]
Agree that that shouldn't be persisted, as it could get stale etc. True that it would create some caching work for me, as I have to recreate the webview and thus Ed from scratch on any device rotation, multi-window-resize etc. Not impossible though. Don't have strong opinions either way.

**Comment by nickvelloff** [comment]
@forresto I also agree it should not be persisted. Given the way it works on iOS right now, I don't think it will affect me.

**Comment by nickvelloff** [comment]
I guess this does affect the Client A/B sync to a degree. You wouldn't see progress upon handoff.

**Comment by forresto** [comment]
A/B isn't going to be really supported until we have an `item/transform` API endpoint for collab. Which will be fun.

**Comment by nickvelloff** [comment]
👍 OK then I'm good with it.

**Comment by forresto** [comment]
@hannesstruss how about an `ed.getState({content, coverPreviews, placeholderInfo})` helper and adding `coverPreviews, placeholderInfo` to the initial props on mount?

**Comment by hannesstruss** [comment]
@forresto Not sure I understand the signature of `ed.getState({content, coverPreviews, placeholderInfo})` correctly – that would be a function that takes an object and returns the state?

as for adding cover previews and placeholder info to initial props, I'd rather just call the setters initially, would that also work?

**Comment by forresto** [comment]
@hannesstruss calling setters is cool.

**Comment by forresto** [comment]
Since it's a breaking change, I'm going to rename the method `updateProgress`, since it can be called for non-`placeholder` blocks that can change cover.
