### ISSUE TITLE
importing Ed Component fails

### ISSUE THREAD

**Issue by netlemur** [the-grid/ed#241]
When importing `import Ed from '@the-grid/ed'` (ed 0.15 or higher) in a fresh webpack/es6 project the browser fails with `localhost/:1 Uncaught SyntaxError: Unexpected token import`

Is there any more (webpack?) config needed to get this running?

**Comment by forresto** [comment]
Probably have to babel whiltelist it, something like

``` js
{
  test: /\.js$/, 
  loader: 'babel-loader', 
  include: [
    path.resolve(__dirname, 'node_modules', '@the-grid', 'ed')
  ]
}
```

**Comment by forresto** [comment]
The other fix would be to build es5 for npm, but we would want to exclude `React` etc, and we would need to maintain the current build for the other clients.

**Comment by forresto** [comment]
Going with a straight babel src → dist setup. Should React be a peer dep in this case? That's what [Rebass does](https://github.com/jxnblk/rebass/blob/master/package.json#L20).
