### ISSUE TITLE
Article blocks: allow removing cover image

### ISSUE THREAD

**Issue by bergie** [the-grid/ed#243]
Sometimes there simply isn't a usable cover image for an article. In these cases, it would be nice to be able to remove the cover image, since they aren't required for article blocks

![screenshot_20160616-162923](https://cloud.githubusercontent.com/assets/3346/16120421/b4e5b97e-33df-11e6-8481-addadaa770a1.png)

**Comment by forresto** [comment]
Good point. Will add `removeCover` to Ed's block schema where applicable https://github.com/the-grid/ed/blob/master/src/schema/block-meta.js
