### ISSUE TITLE
Image received in DS as article blocks

### ISSUE THREAD

**Issue by cbchouinard** [the-grid/ed#249]
We create for this site a post with a title and 4 images and we received in DS an item with one h1 block and 4 articles blocks. Article block html: 

```
<article><img src=\"https://s3-us-west-2.amazonaws.com/the-grid-img/p/1dfa52d91f024522a50372f60b7b3a434844ed1f.jpg\"></article>
```

These 4 images should have been image blocks.

**Comment by forresto** [comment]
Can't repro; maybe old webapp hack.

**Comment by bergie** [comment]
Seems like side-effect of the-grid/html-flatten#60. Will deploy fix as soon as GitHub works properly again

**Comment by bergie** [comment]
See also #250
