### ISSUE TITLE
Pasted image link becomes article block

### ISSUE THREAD

**Issue by narrowdesign** [the-grid/ed#250]
3 of these logos were uploaded and 3 were pasted links to images.
All above the fold.
https://github.com/the-domains/design/blob/master/_posts/2016-07-11-logos.md

The uploaded images became image blocks.
The pasted images became article blocks.

![image](https://cloud.githubusercontent.com/assets/440221/16773338/9de091f4-4825-11e6-9908-6facad0de259.png)

**Comment by narrowdesign** [comment]
And I just realized, I can paste a screengrab from CMD+CTRL+SHIFT+4 into this Github comment and it becomes a PNG! Amazing. Is that possible in ED?

**Comment by narrowdesign** [comment]
![image](https://cloud.githubusercontent.com/assets/440221/16773459/0d904a80-4826-11e6-89e0-f02be5f8727c.png)

**Comment by narrowdesign** [comment]
Here's one uploaded and one pasted side by side:

![image](https://cloud.githubusercontent.com/assets/440221/16773492/2ae0d686-4826-11e6-8585-406829418eda.png)

**Comment by bergie** [comment]
I think the pasted links become article blocks due to the `share` flow (the-grid/harpy). Would need to figure out how to get Embed.ly to distinguish that these are _only_ images.

**Comment by bergie** [comment]
However, looking at https://raw.githubusercontent.com/the-domains/design/master/_posts/2016-07-11-logos.md it seems like they ended up being normalized to img blocks later on?

**Comment by bergie** [comment]
Moving this to the-grid/html-flatten#60
