### ISSUE TITLE
Weird link behavior

### ISSUE THREAD

**Issue by aretecode** [the-grid/ed#258]
https://www.dropbox.com/s/rm93mc1j4q63bg2/editor%20confusing.gif?dl=0

Steps to reproduce:

1) Enter a link
2) Press [enter] key

**Comment by forresto** [comment]
@aretecode That's by design as far as I can see. Webapp should set status text in the blue bar: "Sharing http://test.com/" and progress of the share.

**Comment by forresto** [comment]
@aretecode can I close this as "by design" or can you make a suggestion?
