### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function for the `rounded` prop on `ButtonOutline`

### ISSUE THREAD

**Issue by netlemur** [the-grid/ed#259]
Currently seeing this with ed 0.18.2:
![screen shot 2016-07-31 at 23 12 09](https://cloud.githubusercontent.com/assets/773681/17284978/57bb1466-5774-11e6-80db-6a8d436c3479.png)

More info here: https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by forresto** [comment]
Maybe something changed with Rebass 0.3.0... though I don't see those errors locally. Will poke more.

**Comment by forresto** [comment]
ButtonOutline href PropTypes looks standard: https://github.com/jxnblk/rebass/blob/297cd65669f9769b5a2c7125d0a79d2a57aedd72/src/ButtonOutline.js#L31

**Comment by forresto** [comment]
@jxnblk anything obvious here?

**Comment by forresto** [comment]
@netlemur did you figure out if it's material-ui?
