### ISSUE TITLE
Article Title and Description disappear

### ISSUE THREAD

**Issue by narrowdesign** [the-grid/ed#263]
If you delete the title of an article, the field disappears, leaving only the caption field.
1. Paste a link to an article in Ed.
2. Delete the title and description.
3. Click out of both fields.
4. Watch Title and description be replaced by "Caption" field and no way to add a title or description.

![image](https://cloud.githubusercontent.com/assets/440221/17834576/063fbb40-6715-11e6-8d93-f8737660130a.png)

![image](https://cloud.githubusercontent.com/assets/440221/17834589/9b45cc48-6715-11e6-8824-ba2b93c063d9.png)

**Comment by narrowdesign** [comment]
Related, when pasting an image url, it is treated as an article but there is no way to add a title or description, only a caption.

**Comment by forresto** [comment]
Weirdly, this is by design, since API has different patterns for saving each block: https://github.com/the-grid/ed/blob/8db57524b6f27879178c93a849e6c510a9d6aa5f/src/schema/block-meta.js 

... but maybe we should take a stab at making these things consistent ed⇄api→ds?
