### ISSUE TITLE
Cursor insertion in incorrect location

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#267]
Ed 0.19.4 iOS 9.3.4 iPhone 6s Plus
![img_6090](https://cloud.githubusercontent.com/assets/885369/18084040/9a708820-6e5a-11e6-8971-f1148da8813c.PNG)

_Previously..._ https://github.com/the-grid/ed/issues/99

**Comment by forresto** [comment]
Can you type there? Does it break the doc?

**Comment by nickvelloff** [comment]
Nope. Doesn't insert characters and does not break the doc.

**Comment by nickvelloff** [comment]
Closing, no longer relevant.
