### ISSUE TITLE
json for menu items - ordered

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#270]
Would it make sense to have Ed maintain ordering of menu items in `onCommandsChanged` payload? Some structure like this for example? Low priority of course. 

``` JSON
[
  {
    "type" : "undo",
    "state" : "inactive"
  },
  {
    "type" : "grouped",
    "state" : "inactive",
    "items" : [
      {
        "type" : "heading1",
        "state" : "inactive"
      }
    ]
  }
]
```

**Comment by forresto** [comment]
Thinking to make it flat was to leave presentation up to y'all.
