### ISSUE TITLE
ed.execCommand(commandName) - some commands don't seem to apply change

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#273]
With `ed.execCommand(commandName)`.

This testing is not comprehensive, and only initial feedback.

Thus far commands confirmed to **work correctly** are:
link:toggle
paragraph:make

And do not seem to work:
strong:toggle
em:toggle
ed_upload_image

**Comment by forresto** [comment]
I just tested on ipad safari (with `ed.execCommand('strong:toggle')` in remote console) and they worked. 🤔

**Comment by Eke** [comment]
`ed_upload_image` is disabled by me, have not implemented image picker yet.

`strong:toggle` and `paragraph:make` are working for me. Tested on iPhone 6, iOS version 9.3

**Comment by nickvelloff** [comment]
Removing that css fixed this too. cc @Eke
