### ISSUE TITLE
iOS - possibly related issues. editable that should not be

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#274]
I'm unclear if these are all related, but perhaps they are:
- Button not clickable, text errantly editable ![](http://g.recordit.co/Ob0g9tYMe1.gif)
- Ability to delete UI not meant to be editable ![](http://g.recordit.co/vzTN1Df4Ul.gif)
- Clicking more button in media widget triggers `No Replacement Found` tip and does not allow click ![](http://g.recordit.co/zmpf4agFVz.gif)
- Selecting quote deletes some content, Bold on selection has no effect, List tap deleted some content and appeared to nest list in the quote ![](http://g.recordit.co/v9iuVkLiTn.gif)

**Comment by forresto** [comment]
@nickvelloff did you leave that css on all div???

``` css
/* 👎 */
div {
  -webkit-user-modify: read-write-plaintext-only;
}
```

**Comment by forresto** [comment]
Bet you did... in Safari (edit: Chrome too) apparently that's another way to set contenteditable: http://jsbin.com/cecaya/edit?html,css,output

**Comment by nickvelloff** [comment]
@forresto Ah ha! indeed I did. I'll confirm removing it resolves and see what remains! Phew!

**Comment by nickvelloff** [comment]
Wow. That wreaked all kinds of havoc. Removing fixed it.
