### ISSUE TITLE
losing tweet meta

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#279]
API sends a tweet (without image) as a `quote` block, which is the same as if you save `<blockquote>` html. 

Ed will have to do some special casing to render the attribution version as media and non-attribution as (PM) text.

cc @d4tocchini

**Comment by forresto** [comment]
This line is what blocks loading a `quote` type from a url share, and it's _not_ a quick fix: https://github.com/the-grid/ed/blob/dd199251a6107adf950f25af3703a36a50695b4d/src/store/ed-store.js#L477

**Comment by bergie** [comment]
Quotes generally are from somebody, so attribution support for all quotes makes sense, not only for tweets

**Comment by forresto** [comment]
Blocks get either attribution or formatting, not both, so I don't want to load all `<blockquote>`s in the widget.

**Comment by bergie** [comment]
Ideally there should be no difference in content between something that was shared via URL, and something user constructs by themselves in the editor

**Comment by forresto** [comment]
Maybe time to dive into floating attr...

**Comment by forresto** [comment]
Rolling with the temporary solution of not supporting formatting in `quote` blocks (treat them as media), which fixes the more-common issue of:
- text tweet shares not working
- tweet attribution not shown / saved
