### ISSUE TITLE
make menu bar more responsive

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#281]
Everything that doesn't fit under [...] item.

Use space with button labels, reduce to icon.

![before](https://cloud.githubusercontent.com/assets/395307/18800741/9b7324c0-81ac-11e6-91f1-8d569ebb8940.png)

**Comment by forresto** [comment]
- move image hint down
- remove top padding

![progress](https://cloud.githubusercontent.com/assets/395307/18801589/a3840d0a-81b1-11e6-80df-d7430c57d20f.png)

**Comment by bergie** [comment]
Note: vertical space is at premium when you have an on-screen keyboard covering half of the viewport

**Comment by nickvelloff** [comment]
I do like the clarity that the words in the menu provide (Upload Image)... but I wonder if we gain more with less verbosity if we can accomplish less vertical space on small screens.

**Comment by hannesstruss** [comment]
I think it's fine to shove buttons into an overflow/kebab menu, or group related buttons into menus (e.g. group _bold_, _italic_, _underlined_ into _formatting_ on small screens).

**Comment by bergie** [comment]
Pull-down menus can be problematic as they can clash with the native selection toolbar. I liked the h1-h2-p cycler button we had in a previous editor

**Comment by forresto** [comment]
Going to ship this before I go deeper into menu "[...]" because PM 0.11.x's breaking changes.

![two rows](https://cloud.githubusercontent.com/assets/395307/18850845/4f967c5c-8407-11e6-8a59-9cc74d990a1e.png)
