### ISSUE TITLE
Can't make titles link

### ISSUE THREAD

**Issue by narrowdesign** [the-grid/ed#283]
Created an H1 with 3 words. Selected those 3 words. There's no option to make them a link unless I add a space before the words.
![link](https://cloud.githubusercontent.com/assets/440221/18811729/995236c8-8287-11e6-88fb-d97407af59cb.gif)

**Comment by forresto** [comment]
The block menu shows up when the whole block is selected... that's the difference. I'll see if I can keep the other applicable options in there.

**Comment by narrowdesign** [comment]
@forresto still seeing the same behavior. Do I just need to change my behavior? It's the most common thing I do aside from pasting image links.

**Comment by forresto** [comment]
@narrowdesign webapp hasn't shipped it yet.
