### ISSUE TITLE
Can't Delete Line Break Above Image

### ISSUE THREAD

**Issue by webbjordy** [the-grid/ed#284]
When an empty line is above an image at the top, it can't be deleted to have the image to move up to the top. If the user then attempts to use a backspace to delete the line, the image block gets selected and then deleted.

Steps to reproduce:
- Open Ed
- Make a single line break
- Upload image
- Attempt to delete line break

![linebreak](https://cloud.githubusercontent.com/assets/15053015/18813130/b4e1a6fc-82a1-11e6-8db1-85cbfa1ab514.gif)

**Comment by forresto** [comment]
This is ProseMirror's design choice... we can hack around it, but I don't think it is 🔥 

You can select the first block by pressing escape, then delete it.

FYI, blank lines don't get output when you save.

**Comment by webbjordy** [comment]
@forresto I think we can just close this out. That's a good enough explanation for this imo. If we get increasing reports/complaints about this we can re-open it and explore a hackaround for it.
