### ISSUE TITLE
on 🔗 populate link if selected text is link

### ISSUE THREAD

**Issue by aretecode** [the-grid/ed#288]
## ed

https://www.dropbox.com/s/y067gp05zk1ek4f/ed-link.gif?dl=0
https://www.dropbox.com/s/hi58udvw62sowr9/editor%20tooltip.gif?dl=0
## gmail

https://www.dropbox.com/s/1uu2i7r7xys1l3b/gmail%20ed.gif?dl=0
## vs

it takes many more steps to make something a link with ed:
1. select text
2. click link
3. enter the same text as link
4. enter the same text as title
5. click enter

vs gmail:
1. select text
2. click link - auto uses same text as link and title, then allows you to change it if you want to
## main point

Would it be unreasonable to think that Google has a lot of data about peoples interactions?

Doesn’t it make sense to 
1. have our ux follow patterns that billions of people are familiar with?
2. make it easy with 1 click, and then people who want to change extra (advanced) details, can do so if needed?

**Comment by forresto** [comment]
![ed-link-url](https://cloud.githubusercontent.com/assets/395307/21828219/514b06f4-d75d-11e6-983e-fa78f64e591e.gif)
