### ISSUE TITLE
Ed 2.0.0 - iOS Touch block "snaps" scroll position

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#311]
Touching the interface causes the scroll position to snap to a location. Perhaps that position is the top of the block touched. 
https://www.youtube.com/watch?v=F5xbo3f4Sbk

I'm labeling anything "blocker" that I know we can't ship 2.0.0 with... hope that is appropriate. LMK if I should approach it differently 🙇

**Comment by forresto** [comment]
Yeah... Probably should not be touchstart 🤔

**Comment by forresto** [comment]
muy simplificado: https://github.com/the-grid/ed/commit/9e9532ff9af1307757d71e068460421c0f29b446

**Comment by nickvelloff** [comment]
@forresto awesome!
