### ISSUE TITLE
link:toggle dance for native menu / input

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#314]
* Existing `ed.execCommand('link:toggle')`
  * If link is selected, removes link
  * Otherwise, call new callback prop `onRequestLink` to show modal
    * Call `ed.execCommand('link:toggle', {href, title})` (title optional) to set link of current selection

@nickvelloff OK to overload 'link:toggle' like that? Or should it be a new Ed method?

**Comment by hannesstruss** [comment]
Sounds good to me! Since Ed/Apps are in sync, we can also change that later on.

**Comment by nickvelloff** [comment]
@forresto overload is 👍
