### ISSUE TITLE
Firefox: upload demo not triggering picker

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#44]

**Comment by forresto** [comment]
Yuck, [somewhere in there is something](https://github.com/ProseMirror/prosemirror/blob/482c482d0ed62a0a1e741ce6d103f76fec1a8e8f/src/menu/menu.js#L149-L152) that makes Ff think that the input.click() isn't triggered from a user click.

**Comment by forresto** [comment]
Call stack in Ff. The original MouseEvent `isTrusted` but something in there (though it looks synchronous) is making it ignore the `input.click()`

![screen shot 2016-02-01 at 5 01 39 pm](https://cloud.githubusercontent.com/assets/395307/12732900/bdd34faa-c905-11e5-8603-ff8ab926008f.png)

**Comment by forresto** [comment]
@marijnh This is a strange issue. I'm trying to trigger a [file input click()](https://github.com/the-grid/ed/blob/33be21dddf84bbdbf9ec29e5165e69e4b2e7301d/demo/demo.js#L34-L48) from a tooltip menu [custom button](https://github.com/the-grid/ed/blob/39d6159794d9119dd627d59a6fd66cda5c580a02/src/edit/ed-commands.js#L9). I think somewhere in the call stack above Firefox stops trusting that the input.click() originated from a human click. [Signalling directly](https://github.com/the-grid/ed/blob/33be21dddf84bbdbf9ec29e5165e69e4b2e7301d/demo/demo.js#L82-L84) from a button click works.

Could there be a way to have more direct access to the dom / event of a custom menu item?

**Comment by marijnh** [comment]
@forresto I don't really understand what you are doing, but trying to simulate browser events on menus to activate commands seems like the wrong approach. How about you call `exec` on the command object directly?

**Comment by forresto** [comment]
@marijnh I'm using the real menu item click to call trigger the hidden file input dialog by calling `input.click()`.

I found the Firefox issue with this: PM's [renderIcon](https://github.com/ProseMirror/prosemirror/blob/482c482d0ed62a0a1e741ce6d103f76fec1a8e8f/src/menu/menu.js#L149) listens to `mousedown`. 
`click` and `mouseup` would work for this case.

If PM needs to stick with `mousedown`, I'll need another way to make that menu item to make my own listener.

**Comment by marijnh** [comment]
Which file input dialog is this? ProseMirror doesn't define any such dialog.

**Comment by forresto** [comment]
I'm trying to not rewrite the menu system :smiley: by making a [custom block menu item](https://github.com/the-grid/ed/blob/33be21dddf84bbdbf9ec29e5165e69e4b2e7301d/src/edit/ed-commands.js#L3-L16) that our [file upload code](https://github.com/the-grid/ed/blob/33be21dddf84bbdbf9ec29e5165e69e4b2e7301d/demo/demo.js#L34-L48) can get triggered by.

**Comment by forresto** [comment]
Is there a reason that PM's renderIcon listens to `mousedown` and not `click`?

**Comment by marijnh** [comment]
Yes, if you preventdefault mousedown, focus stays where it is, whereas on click, the focus has already been moved.

I'm going to push a big change to the way menus are rendered and composed either today or tomorrow. It will probably make it easier for you to do what you want (you can then just drop anything that has a `render` method into your menu structure, so defining custom elements becomes much easier).

**Comment by forresto** [comment]
Cool!

I'll still want to know the `Pos` where the menu item was triggered, so the focus stuff will be relevant. Will keep that in mind.

**Comment by forresto** [comment]
Seems I can't make my own menu element with click handler, because PM is still attaching the `mousedown` listener here https://github.com/ProseMirror/prosemirror/blob/c16bee8a346ea90ca360616f50c43cebb868bfc4/src/menu/menu.js#L87-L91

**Comment by marijnh** [comment]
For custom behavior, you'll want to define your own class with its own `render` method. `MenuCommand` instances are simple clickable command icons.

**Comment by forresto** [comment]
Got stuck, asked here: https://discuss.prosemirror.net/t/custom-menu-item-class-more-examples-please/235/3?u=forresto
