### ISSUE TITLE
setContent with article throws error

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#50]
Using ed 0.0.35 and this flow:
1. Hit enter to create new block
2. Paste URL, hit enter
3. App gets url share event, creates placeholder block, does `setContent` (placeholder is displayed correctly)
4. App does `PUT /item/<id>` to save placeholder block to API
5. App does `POST /share` into the placeholder block
6. As soon as job-completed GCM comes in, app reloads item and does `setContent`

This is the item (I do `ed.setContent(item.content)`): https://gist.github.com/hannesstruss/819ab983c52cca26251c

This is the error (the index in `Failed to resolve path %d` is the index of the block about to be replaced +1, when counting 0-based):
![developer_tools_-_file____android_asset_posteditor_editor_html](https://cloud.githubusercontent.com/assets/115381/12841990/1bb6e5f4-cbf0-11e5-9014-7cc0f30d69cf.png)

Not sure how related they are and can't reproduce, but I also encountered these errors (might have happened during just editing):
![developer_tools_-_file____android_asset_posteditor_editor_html](https://cloud.githubusercontent.com/assets/115381/12842006/2c7e9e90-cbf0-11e5-8182-10e7329e563f.png)

![developer_tools_-_file____android_asset_posteditor_editor_html](https://cloud.githubusercontent.com/assets/115381/12842094/c0ad4828-cbf0-11e5-932c-4e81016b3128.png)

(Sorry for screenshots, but I can't seem to copy/paste stacktraces from Chrome devtools)

**Comment by forresto** [comment]
Let's see if PM 030 fixes this :tophat:

**Comment by forresto** [comment]
I think this is b/c it tries to put caret in the placeholder block. Need to tweak the selection restore logic to take this into account.

**Comment by forresto** [comment]
(Another reason for Ed to do the actual placeholder block splicing.)

**Comment by hannesstruss** [comment]
The caret theory seems likely: with ed .37 (uses PM 0.3.0 right?), upon `setContent`, the placeholder block is focused (blue border on Android). (but still doesn't update).

**Comment by hannesstruss** [comment]
@forresto how could the API for splicing within ed look like?

**Comment by hannesstruss** [comment]
This is blocking editor integration on mobile, would be great to prioritize! :bow:

**Comment by forresto** [comment]
`ed.spliceContent(index, deleteCount, blocks)`

or `ed.insertBlocks(index, blocks)` and `ed.replaceBlock(index, block)`

instead of 

```
  let content = ed.getContent()
  content.splice(index, 1, block)
  ed.setContent(content)
```

---

**Comment by forresto** [comment]
Thinking more, `setContent` needs to work no matter what you throw at it (with merging logic). So I'll make it work without changing API first.

**Comment by forresto** [comment]
0.0.40 rolling out, should hopefully fix it.

**Comment by hannesstruss** [comment]
I'm getting this error now:
<img width="423" alt="developer_tools_-_file____android_asset_posteditor_editor_html" src="https://cloud.githubusercontent.com/assets/115381/13026935/4531056c-d23b-11e5-9c3c-9cce58b317ff.png">

**Comment by forresto** [comment]
The way that I did the demo (replacing url's p block with placeholder on App side) is fundamentally against the merging strategy: only placeholders can be updated from app. Ed needs to turn the p into a placeholder, then hit `onShareUrl` with the index of the existing placeholder ready for updates. The app shouldn't do the block splicing (at least for the url case, where a text block changes to a placeholder).

For `onShareFile`, injecting `n` file blocks above the caret is different, because no blocks change from text to placeholder.

**Comment by hannesstruss** [comment]
I'm getting a selection error again with 0.1.2:
![developer_tools_-_file____android_asset_posteditor_editor_html](https://cloud.githubusercontent.com/assets/115381/13076433/89deaa1a-d4b2-11e5-930e-44a86d17ede7.png)

I think the following happens:
1. I paste URL, hit enter
2. Ed creates placeholder, notifies app
3. App gets content, does `PUT /item/<id>`
   1. :point_right: At this point, the content array has two blocks. The placeholder, and an empty block in which the caret was after hitting enter. App pushes both placeholder and empty block to API.
4. App does `POST /share`.
5. :point_right: For some reason, API seems to discard the empty block:
6. Job completes, App fetches item, does `setContent` (content array length is `1`, only contains article block)
7. :bomb:

**Comment by hannesstruss** [comment]
@bergie is the discarding of the empty block expected? Shouldn't break Ed anyway I guess, just interested.

**Comment by bergie** [comment]
@hannesstruss API ditches empty or invalid blocks when saving

**Comment by forresto** [comment]
@hannesstruss That one makes sense. I'll make merging actually work (now it just uses new) and write some specs around that.

**Comment by hannesstruss** [comment]
0.2.0 doesn't throw an error anymore, but the placeholder doesn't get replaced on `setContent`. Content array contains only one block, this is how I get the item from the API (snipped histogram data): https://gist.github.com/hannesstruss/4e6e61c99db17eef4ada

Already thought block IDs might change in the process, but it remained the same from placeholder creation to `setContent`.

**Comment by hannesstruss** [comment]
Just noticed this: when the item comes back from the API, it still has `metadata.status` set to `sharing...` – does that cause Ed to display a placeholder?

**Comment by bergie** [comment]
@hannesstruss correct, APIs doesn't nuke metadata from the placeholder, so users can set titles/attributions/whatever even while upload is going

**Comment by hannesstruss** [comment]
Tried to remove `metadata.status` in app before `setContent`, but placeholder still isn't replaced

**Comment by hannesstruss** [comment]
When I do `ed.getContent` it returns the correct content I have passed to `setContent` before.

**Comment by forresto** [comment]
@hannesstruss widget types are set by block.type, so no. 

I tweaked how merging works and added more tests in 0.3.0 ... if that doesn't fix it I need to reduce it to a test. Though I thought this would be your case: https://github.com/the-grid/ed/blob/69759d872d5e8a3abb86f656cc5e9def913c0931/test/ed.js#L119-L137 (replaceBlock done internally by url plugin)

**Comment by forresto** [comment]
I can also extend the shares in the demo for the :monkey_face: test side.

**Comment by hannesstruss** [comment]
The merging seems to be working fine, `getContent` and even `ed.pm.doc.content.content` look good. Just the DOM isn't updated: http://hs-random.s3.amazonaws.com/ed-set-content.mov

**Comment by hannesstruss** [comment]
:boom: :boom: :boom: 
![db1fuxjlsi](https://cloud.githubusercontent.com/assets/115381/13119042/633971e2-d5a7-11e5-8e5b-a37c7e27f748.gif)
Thanks @forresto! :hand:
