### ISSUE TITLE
Handling share failures

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#59]
We need a way to handle failures when sharing. Currently, sharing works like this:
1. User triggers share
2. Ed creates placeholder, notifies app with `{blockId, url}` (in case of URL sharing)
   - _Update:_ When sharing images, App creates placeholders and does `ed.setContent`
3. App does `ed.getContent()`, `PUT /item/<id>` and `POST /share`
4. When share is done (App receives GCM/APN), App does `GET /item/<id>`, then `ed.setContent(blocks)`

Possible fail cases (ignoring programmer errors):
1. ~~When sharing images: User closes image picker without picking images~~ -- _not an issue b/c App inserts placeholders after files are selected - fo_
2. `PUT /item/<id>` fails
3. `POST /share` fails
   1. Special case when sharing images: only some `POST /share` calls succeed
4. `POST /share` succeeds, but the app isn't notified, or the share job takes a long time api-side
5. `GET /item/<id>` fails

Questions:
1. [ ] We need UX for failures. I think V1 shouldn't include retrying. I'd go for something like "make placeholder block red, add X button to remove the failed block"
2. [ ] We need an API in Ed, so App can notify Ed of failures. Since Ed already creates the placeholders itself, I think it should also modify/remove them. Off the top of my head: `ed.shareFailed(placeholderBlockId)`.
3. Should we timeout when the Share job doesn't complete within X minutes? It could result in false positives, where the user thinks the share failed, does something else/closes the editor, and the shared content eventually ends up in the item unexpectedly.
4. It's probably not a big problem if some but not all image shares fail. Some placeholders become red, some get replaced with images.
5. When sharing images, Ideally we only create the placeholder blocks after the user has already selected `n` images, so we don't have to remove them again.

cc @forresto @nickvelloff @JohnRandom

**Comment by nickvelloff** [comment]
@hannesstruss that is quite a few fail cases to try to cover, and mobile exasperates them. Multiple, dependent, async operations are prone to error that are dependent on an ephemeral client runtime. 
I don't have an answer that wouldn't require a different share technical design. Look forward to thoughts here.

**Comment by forresto** [comment]
@hannesstruss with merging in 020 Ed has to make the placeholder block for the URL share, since it is text → placeholder. Apps still make placeholder for uploads, because Ed doesn't know how many files would be picked (or 0), and for the merging adding new placeholders is OK.

**Comment by hannesstruss** [comment]
@nickvelloff this all happens while the editor UI is visible and in foreground. Are those operations also prone to be cancelled by iOS? Interested in how that looks like, are you using [NSOperation](http://nshipster.com/nsoperation/)?

@forresto Should we unify this, make Ed always create placeholder blocks, e.g. by adding something like `ed.createPlaceholders(afterBlockId, numberOfPlaceholders)`?

**Comment by forresto** [comment]
What about `ed.insertBlocks(index, blocks)`? Then blocks could be initialized with `metadata.status` with filename etc. Keeping index simplifies things (PM-made text blocks don't have `id`).

I'd keep the `setContent` merging for server updates (placeholder → image etc).

**Comment by nickvelloff** [comment]
@hannesstruss They are not likely to be cancelled which is good, but I'm more concerned with the "middle state" cases where the `placeholder` is created, the `PUT` succeeds but the share fails (network related or something). Or say the `GET /item/<id>` fails after it all. 
The timing out and clearing stale empty placeholders approach is a possible solution. This would need to be server side as the client may not be active.
Just seems like there are a lot of cases things could get out of sync.

Perhaps I'll just implement and see what I run into.

**Comment by nickvelloff** [comment]
@forresto Share failures are likely a V1 need right? Should be part of `4.0.0`?

**Comment by nickvelloff** [comment]
From Slack

Forrest Oliphant [3:15 PM] 
Could have a failed state with an X... eventually if people can change meta while uploading then we'll want to retry to same placeholder.

Nick Velloff [4:01 PM] 
@forrest: If we could just do a failed state (perhaps red text or something) with an X I think it would work for a long time. A case I run into right now is many URLs will fail ​_every_​ time like http://uber.com … no way to recover.

**Comment by forresto** [comment]
`ed.updatePlaceholder(id, {status, progress, failed})` with 0.7.0 (#136)
