### ISSUE TITLE
iOS - Sticky toolbar does not stick

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#69]
<img width="487" alt="screenshot 2016-02-17 21 11 27" src="https://cloud.githubusercontent.com/assets/885369/13134429/1cd0e154-d5bb-11e5-8871-b34985d56ed3.png">

**Comment by nickvelloff** [comment]
There are 2 different issues shown in this video.
1. When not editing (no keyboard) the toolbar disappears and re-appears
2. When editing the toolbar scrolls up and does not re-appear
![ed-bug](https://cloud.githubusercontent.com/assets/885369/13307066/9a99740e-db1d-11e5-909c-ff5d9649c1be.gif)

**Comment by nickvelloff** [comment]
@forresto this fix is definitely MVP for v1.

**Comment by nickvelloff** [comment]
@hannesstruss does this happen on Android?

**Comment by hannesstruss** [comment]
No, not that intensely – the toolbar jumps a tiny bit when I start scrolling down from the very top though: [editor-toolbar-jump.mov](https://files.zenhub.io/56ced12934ab40f92bc770ac)

**Comment by forresto** [comment]
Looks like it it is stuck, but behind the black header? Could adding some body padding-top to your version of the html help?

**Comment by nickvelloff** [comment]
I believe it actually disappears but I'll make header transparent to test.

**Comment by nickvelloff** [comment]
So the toolbar visibility is actually toggled, so I don't think padding would have an effect.

**Comment by nickvelloff** [comment]
FWIW the web view itself is constrained such that the webview.top = header.bottom

**Comment by nickvelloff** [comment]
Logged issue upstream https://github.com/ProseMirror/prosemirror/issues/223

**Comment by nickvelloff** [comment]
@forresto feel free to close unless you want to track here

**Comment by forresto** [comment]
Let me try making it more sticky first.

**Comment by nickvelloff** [comment]
:+1: If we can do it without it turning into a huge time suck for you it would be :dancers:

**Comment by forresto** [comment]
Is `absolute` broken in the same way as `fixed`? Could hack it with that on scroll.

**Comment by forresto** [comment]
Will try.

**Comment by nickvelloff** [comment]
👌🏻 let me know if I can help try anything

**Comment by nickvelloff** [comment]
It's certainly better. Usable at least.
![ed-bug-lose-heading-fix](https://cloud.githubusercontent.com/assets/885369/13374681/e50282a4-dd40-11e5-9a63-e1d0baec19b0.gif)
