### ISSUE TITLE
images: edit cover source

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#71]
Need clarification from API (@bergie) about a consistent way to save that for all types that can have a cover.

**Comment by forresto** [comment]
@bergie metadata.src?

**Comment by bergie** [comment]
Unless we want to change how APIs handle them, the image source is expected to be in HTML

**Comment by forresto** [comment]
That isn't consistent for `video` and `interactive` type blocks.

**Comment by bergie** [comment]
- Image blocks: `<img src="xxx">`
- Article blocks: `<article><img src="xxx"></article>`
- Video doesn't support custom covers yet, though we should add support via [`poster` attribute](https://developer.mozilla.org/en/docs/Web/HTML/Element/video) (needs support in html-flatten and Caliper)
- Interactive blocks don't have covers

**Comment by forresto** [comment]
Apps (@marsch @netlemur @nickvelloff @hannesstruss): how is this for the event to request app to upload a new image for a block cover?
1. `options.onRequestCoverUpload: function (blockId) {}` (similar to `onShareFile`, but hit with block id instead of index)
2. Once upload is complete, app can hit `ed.setCoverSrc(blockId, url)`

---

I think that if I make UI to change a cover to an image URL, then I can verify that and make an imgflo link within Ed. Then apps would just get a `change` event.

**Comment by nickvelloff** [comment]
@forresto LGTM 👍

**Comment by hannesstruss** [comment]
@forresto I'd prefer keeping Ed API as small as possible, but this works for me.

**Comment by forresto** [comment]
@hannesstruss this is as small as possible though, right? It _could_ be an accepted mutation to pick out from setContent, but that would involve apps and ed both climbing into `content`, which is against the principle that Ed is responsible for that data.

**Comment by hannesstruss** [comment]
Yep :) 👍

**Comment by forresto** [comment]
We'll need another method for avatars #132, but that's for later.

**Comment by forresto** [comment]
The other point on this... we can use same `ed.updatePlaceholder(id, metadata)` for new cover upload progress.

---

@marsch or @netlemur does this look good for webapp?

> how is this for the event to request app to upload a new image for a block cover?
> 1. `options.onRequestCoverUpload: function (blockId) {}` (similar to `onShareFile`, but hit with block id instead of index)
> 2. Once upload is complete, app can hit `ed.setCoverSrc(blockId, url)`

**Comment by netlemur** [comment]
unless there are some hidden demons somewhere in the webapp/ed part this looks good to me. /cc @marsch

**Comment by forresto** [comment]
We also have `options.onPlaceholderCancel` which would make sense to hit if the person deletes the block while the upload is happening.

``` js
options.onPlaceholderCancel = function (blockId) {
  /* app should do something with orphaned upload? */ 
}
```

**Comment by bergie** [comment]
For `<video poster="xx">` we'll need noflo/noflo-video#62
