### ISSUE TITLE
Possible inconsistency when deleting placeholder and closing Ed

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#76]
Given the following scenario:
1. User pastes URL, initiates share
2. User deletes placeholder block 
3. App `PUT`s item without placeholder
4. Share job finishes
5. App fetches item, does `ed.setContent`

API might append the share block to the end of the content array if it doesn't find the placeholder. But Ed would just ignore that block, as the merging strategy only replaces placeholders.

As long as the App does a final `PUT` without placeholder or shared block, things are okay though.

**Comment by forresto** [comment]
So is the issue only when I share something, delete the placeholder, then close Ed? Maybe not such a big deal that it pops to end in that case.

**Comment by hannesstruss** [comment]
Yeah, it would only be noticeable if the user stops editing after 5.
