### ISSUE TITLE
onShareUrl failing to fire

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#78]
1. If I add a url, I see this:
2. <img width="487" alt="screenshot 2016-02-23 22 45 22" src="https://cloud.githubusercontent.com/assets/885369/13277642/4db40b70-da7f-11e5-8e3c-c9622becbec3.png">
3.  `onShareUrl` fires properly
4. Then I delete that url.
5. Then I repeat.
6.  `onShareUrl` does not fire subsequently (and there are no js errors).
7. :fearful: 

Additionally:
If an placeholder block exists when the item is loaded, the it will fail after deleting it as well.

**Comment by hannesstruss** [comment]
I can't reproduce that with ed 0.3.1, which version are you on?

**Comment by hannesstruss** [comment]
0.4.1 also seems to work fine.

**Comment by hannesstruss** [comment]
Misunderstood – this actually happens for me too. Paste URL, hit enter, delete placeholder before share completes, paste URL again, hit enter :point_right: placeholder is created, but `onShareUrl` isn't triggered.

**Comment by forresto** [comment]
Deleting the block leaves it in the internal `_content` representation (for widget cut and paste)... might need to rethink how that works with merging.

**Comment by nickvelloff** [comment]
Dupe of https://github.com/the-grid/ed/issues/87
