### ISSUE TITLE
Should we remove excess empty blocks after tapping in the blank space?

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#79]
I like that you can tap in the blank space now to create a new block!

There's a slight inconvenience on Android though. When long pressing on an empty block that is not the last empty block, the in-place context menu for pasting doesn't pop up. Instead, an action mode overlay shows from which people can paste.

Definitely an Android bug, but we might be able to work around that by not leaving empty blocks at the end of the content array. What do you think?

![db1ap5h3i2](https://cloud.githubusercontent.com/assets/115381/13290068/91345c40-db12-11e5-814d-3b74fb3cb97d.gif)

**Comment by forresto** [comment]
If last block is already empty text, just focus it?

**Comment by hannesstruss** [comment]
Not sure that would cut it. On the other hand, people are going to come across this also while pasting normal text in normal blocks. So maybe not worth special casing.

**Comment by forresto** [comment]
Didn't catch the action mode overlay part. So that's when you select whole block?

**Comment by hannesstruss** [comment]
Sorry, let me clarify – In the gif above, you see this popping up: ![should_we_remove_excess_empty_blocks_after_tapping_in_the_blank_space__ _issue__79_ _the-grid_ed](https://cloud.githubusercontent.com/assets/115381/13291527/639a01a8-db18-11e5-9093-815accb9362c.png) That's the in-place popup I mean. It is shown when I place the caret in an empty block, then long-press the caret – but only if there are no further blocks after the selected one.

If there _are_ other blocks after the selected one, the in-place popup won't show, but instead an "action mode overlay" (overlays the app bar on top):

![should_we_remove_excess_empty_blocks_after_tapping_in_the_blank_space__ _issue__79_ _the-grid_ed](https://cloud.githubusercontent.com/assets/115381/13291627/c62a58d6-db18-11e5-8960-7bf8e3aff835.png)

Users might be confused when they long press, but the in place pop up doesn't appear. It can be hard to spot the action mode overlay.. It's a bug in Android-Webview, so we can't fix it 100%. The problem will also occur to users when they try to paste a non-URL somewhere in a non-empty block.

...Also I just noticed that it doesn't occur on my physical device, so probably ¯_(ツ)_/¯
