### ISSUE TITLE
the fold

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#82]
We need to build "the fold" into Ed.
- [title text field, if exists]
- [instance of ProseMirror with schema limited to p, list, quote, inline formatting]
- [buttons to add single title (plain text), single (for now) image OR url share]
- [`hr` equivalent visually denotes fold]
- [full-schema ProseMirror]

Ed should have initial option and method to toggle `collapsed` (only show above the fold) state.

Initial content should infer fold from starred blocks.

`ed.getContent` should build content array with blocks "above the fold" starred.

---

This makes Ed not-insignificantly more complex, but has advantage of working with current API.

**Comment by nickvelloff** [comment]
Is "Remove Block" supposed to work yet?
<img width="185" alt="screenshot 2016-03-22 11 47 40" src="https://cloud.githubusercontent.com/assets/885369/13963784/f8e4200c-f023-11e5-8fc9-9fad8b0ffaae.png">

**Comment by forresto** [comment]
Yes. Caveat: If there is a media block under the fold it will get promoted.

**Comment by forresto** [comment]
The start is done, more work on the flow in #141
