### ISSUE TITLE
URL Share widget border-top overlaps with text block

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#83]
![img_5616](https://cloud.githubusercontent.com/assets/885369/13309727/31a676ec-db34-11e5-8fcd-27e481d343b3.PNG)

**Comment by forresto** [comment]
I've only seen this after #72 :bomb: ... any red in console?

**Comment by nickvelloff** [comment]
I think this was my bad. I think called `window.edMount` more than once and blew things up.
