### ISSUE TITLE
Text block reverts to old value after fetching an updated item (gists included)

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#84]
1. Initial load of item data: https://gist.github.com/nickvelloff/6e8bc69ba717a3c36939
2. visual state of content:
   ![img_5617](https://cloud.githubusercontent.com/assets/885369/13311249/9aba5e52-db41-11e5-8638-5c01a9045b53.PNG)
3. Edit some textual content, type "The name is mr ed"
4. PUT succeeds: https://gist.github.com/nickvelloff/d78cd3a558ef36821f4d
5. visual state of content:
   ![img_5618](https://cloud.githubusercontent.com/assets/885369/13311250/9abf78ce-db41-11e5-8326-76e5605fae34.PNG)
6. Receive push notification that the item update is complete
7. GET the updated item: https://gist.github.com/nickvelloff/e59162feed3fe82ab541
8. `"window.ed.setContent(\(contentString));` the new item data
9. visual state of content (text reverts to old value):
   ![img_5619](https://cloud.githubusercontent.com/assets/885369/13311248/9a99b58a-db41-11e5-9775-f0d649743fe1.PNG)

**Comment by forresto** [comment]
8) string or array?

**Comment by nickvelloff** [comment]
@forresto It is an array, just a string representation `content.rawString()`. The exact same approach is used to mount Ed successfully `window.edMount(\(contentString));`

**Comment by nickvelloff** [comment]
@forresto 
Just to confirm I re-examined the data being passed to `window.ed.setContent(\(contentString));`

I replaced the content block that contained "Ze Hola 123" with "JIMMY". It reverted back to "Ze Hola 123" after calling `setContent`.

``` JSON
[
  {
    "id" : "c0ef57e6-41d6-4d5e-9d2d-fbfe15c09d0b",
    "created_at" : null,
    "metadata" : {
      "starred" : true,
      "source" : "ea6e66ad-30cb-42df-b989-4c45e5693adc",
      "publisher" : {

      },
      "user" : "368c03f5-d778-420c-b14d-58fd788912e2"
    },
    "item" : "ea6e66ad-30cb-42df-b989-4c45e5693adc",
    "src" : null,
    "type" : "h1",
    "length" : 22,
    "measurementVersion" : 16,
    "updated_at" : null,
    "text" : "Post with editor 0.4.1",
    "language" : "en",
    "measurementHash" : "c938d5baf8e54511b82e8e2ac7abc5dc",
    "html" : "<h1>Post with <strong>editor<\/strong> 0.4.1<\/h1>"
  },
  {
    "id" : "398e944f-f7c1-4764-b70f-95db42b63daf",
    "created_at" : null,
    "metadata" : {
      "starred" : true,
      "source" : "ea6e66ad-30cb-42df-b989-4c45e5693adc",
      "publisher" : {

      },
      "user" : "368c03f5-d778-420c-b14d-58fd788912e2"
    },
    "item" : "ea6e66ad-30cb-42df-b989-4c45e5693adc",
    "src" : null,
    "type" : "text",
    "length" : 17,
    "measurementVersion" : 16,
    "updated_at" : null,
    "text" : "The name is mr ed",
    "language" : "en",
    "measurementHash" : "f30ef47d703bdc5b61162e8345e2faf8",
    "html" : "<p>The name is mr ed<\/p>"
  },
  {
    "id" : "e3ea35d1-53f3-433c-b723-c0667806af73",
    "created_at" : null,
    "metadata" : {
      "starred" : true,
      "source" : "ea6e66ad-30cb-42df-b989-4c45e5693adc",
      "publisher" : {

      },
      "user" : "368c03f5-d778-420c-b14d-58fd788912e2"
    },
    "item" : "ea6e66ad-30cb-42df-b989-4c45e5693adc",
    "src" : null,
    "type" : "text",
    "length" : 5,
    "measurementVersion" : 16,
    "updated_at" : null,
    "text" : "JIMMY",
    "measurementHash" : "199d8713235c98588b5f256f045a5f99",
    "html" : "<p>JIMMY<\/p>"
  }
]
```

**Comment by forresto** [comment]
@nickvelloff confirm this fix with 0.4.2?

**Comment by nickvelloff** [comment]
@forresto yessir on it

**Comment by nickvelloff** [comment]
0.4.2 fixed it :smiley:
