### ISSUE TITLE
iOS - Heading formatting lost upon index change (filed upstream)

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#86]
Verified on PM demo.
Filed upstream https://github.com/ProseMirror/prosemirror/issues/224

**Comment by nickvelloff** [comment]
Just for reference:
![ed-bug-lose-heading](https://cloud.githubusercontent.com/assets/885369/13341324/93acd2ce-dbec-11e5-95dd-2144d6703d9c.gif)

**Comment by forresto** [comment]
This looks OK now. 😎
