### ISSUE TITLE
iOS - Exception when inserting placeholder after deleting placeholder

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#87]
1. Open Post
2. Add Image, inserts placeholder (do not complete placeholder replacement)
3. Delete that placeholder
4. Add another, see exception
   ![screenshot 2016-02-26 02 04 02](https://cloud.githubusercontent.com/assets/885369/13349595/ce32dec8-dc2f-11e5-9624-b84dedd6610a.png)

**Comment by nickvelloff** [comment]
Likely related to https://github.com/the-grid/ed/issues/78

**Comment by forresto** [comment]
Something else should be failing earlier.

**Comment by forresto** [comment]
I think this is fixed with #107 refactor (0.5.0). Reopen if no.

**Comment by nickvelloff** [comment]
@forresto Confirmed!!
