### ISSUE TITLE
Interface for placeholder / preview cover image

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#92]
IOS uploads images rotated only by exif, and API doesn't rotate until measurements are done. We need a way to specify a data URL and dimensions for when apps want to show a preview during upload and before measurements are done. 

Preferably not in content array, so we don't have to worry about stripping them out. 

Need to confirm if we need to be careful to merge new covers in. Current merge only touches placeholder blocks.

**Comment by nickvelloff** [comment]
Will need to see the state of the latest measurements notification. I am not clear exactly how we will map to the appropriate block as I think it only contains the item id.

**Comment by forresto** [comment]
@nickvelloff Maybe wouldn't need to update block with measurement... We're not using it for now.

**Comment by forresto** [comment]
@nickvelloff @hannesstruss @JohnRandom:
What do you think about `ed.setImagePreview(id, src)` for uploading image preview?
`src` could be a `data:` or `blob:` url. Resized to 720 max would help keep things fast.

**Comment by hannesstruss** [comment]
Where would that data live mid-term? I have to destroy+recreate Ed (i.e. the whole webview) when the device is rotated. Would it be attached to the placeholder block?

**Comment by forresto** [comment]
No, I want to avoid Ed state junk in the `content` array.

@hannesstruss would it be possible for you cache them app-side and re-set them after mounting?

**Comment by nickvelloff** [comment]
@forresto `ed.setImagePreview(id, src)` works for me.

**Comment by hannesstruss** [comment]
Yeah, I can make that work. Will make it basically a caching problem, as we'd have to make sure not to keep any of the downscaled images around if they're not needed anymore.

**Comment by forresto** [comment]
@hannesstruss It won't matter so much if Ed is showing the local version. That will help in iOS' case, where the uploaded and blockified but still unmeasured version can have wrong rotation.
