### ISSUE TITLE
quote vs blockquote

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#93]
![ed-bug-quote](https://cloud.githubusercontent.com/assets/885369/13375745/a74675e4-dd5c-11e5-8649-5d1fdc2a76ed.gif)

**Comment by forresto** [comment]
@bergie can API maintain plain `blockquote` type blocks so Ed can keep them in editable flow?

**Comment by bergie** [comment]
Quote block is a quote block, as far as API sees it

**Comment by bergie** [comment]
If you need distinction between quotes with attribution, and without, then looking at metadata might be better than trying to enforce a type that doesn't exist.

Though, how would users do attribution for their quotes then?

**Comment by forresto** [comment]
Ideally, attribution for quote would be line break, dashdash, name, and link it if you want. But if we fill out the meta in a smart way from that html, then we have duplication. 

I can experiment with this more, to figure out some way to keep the html in the editable flow and meta editing attached.
