### ISSUE TITLE
Difficult to insert cursor after an image block

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#94]
I was not able to reproduce this on the PM demo.
![ed-bug-selection](https://cloud.githubusercontent.com/assets/885369/13375788/f354799e-dd5d-11e5-8739-7a6040ab5271.gif)

**Comment by forresto** [comment]
(upstream doesn't have widgets, which cause this issue here)

Looks like `focus` doesn't work in the [tap-add-text plugin](https://github.com/the-grid/ed/blob/d12b957586891d9affeb710314e5b651c047ca7a/src/plugins/tap-add-text.js). Though it does insert the paragraph which you can then manually focus.

(ಠ_ಠ) :apple:

**Comment by forresto** [comment]
@nickvelloff have you tried `webView.keyboardDisplayRequiresUserAction = NO;` ??
http://stackoverflow.com/a/13704691/592125

**Comment by nickvelloff** [comment]
@forresto unfortunately this no longer exists with `WKWebView` and there is no equivalent

**Comment by nickvelloff** [comment]
@forresto FWIW you _can_ do this with the following steps:
1. Scroll way down and click at the bottom to create a block
2. Click that area again to focus
So seems like there are 2 issues
1. Clicking close to the bottom of an image block does not create a new block
2. Focus
What would happen if Ed forced there _always_ to be an insertion area trailing if the last block is an image?

**Comment by forresto** [comment]
That's how old version works: pads out everything with empty `p`s. Between media would be a fix for #96.

**Comment by nickvelloff** [comment]
True. 2 :bird: 1 :moyai: 
I do not know if there would be side effects in DS, so we may want to give @cbchouinard a heads up if we go that route.

**Comment by forresto** [comment]
No, API strips them out: https://github.com/the-grid/html-flatten/blob/2179d2c8f1676f5e8a411210dcf9a12eb6303512/spec/Flatten.coffee#L416-L436

**Comment by nickvelloff** [comment]
I think then that would certainly do the trick :+1:
