### ISSUE TITLE
Currently no way to delete an image block that precedes another image block

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#96]
Because there is not a way to insert the cursor _after_ and image block and _before_ the next one, a user cannot either select a block or backspace to delete it. 

This bit is different from upstream so I'm creating the issue here.

**Comment by nickvelloff** [comment]
Just a thought, as I know this is more complicated (cursor insertion) than it might sound... Maybe just a delete button on these types of elements ("X")?

**Comment by forresto** [comment]
On desktop you can key ↑ ↓ to select media blocks. When one is selected, you can cut, delete, or press enter to make a paragraph following.

I suspect that even if tap-to-select block works in :iphone:, the keyboard will hide. So yeah, need some buttons, maybe in "..." menu for media blocks.
