### ISSUE TITLE
Am I supposed to be able to focus in this position?

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#99]
This may be intentional. 
<img width="487" alt="screenshot 2016-02-29 21 24 19" src="https://cloud.githubusercontent.com/assets/885369/13418516/eaf28268-df2a-11e5-8ae7-bcd29758258f.png">

**Comment by forresto** [comment]
No...

**Comment by forresto** [comment]
@nickvelloff did you tap there or did it end up there after a `setContent` or something?

**Comment by nickvelloff** [comment]
@forresto I tapped in the _perfect_ spot.

**Comment by forresto** [comment]
Fixed with newer PM (I think), otherwise will always be an issue until #77.
